-- ============================================================
-- 023_spark_ai_flag.sql
-- ------------------------------------------------------------
-- Marks questions generated by AI so admins can review them
-- separately from the curated seed bank.
-- ============================================================

ALTER TABLE spark_question_bank
  ADD COLUMN IF NOT EXISTS ai_generated boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS spark_qb_ai_generated_idx
  ON spark_question_bank(ai_generated, active);